### ISSUE TITLE
All .env* files should be ignored during commit!

### ISSUE THREAD

**Issue by acatzk** [Miyunecadz/POSystem#2]
.env* files had a sensitive information in regards to our application if would be best practice to ignored it

```
# local env files
.env*
.env.local
.env.development.local
.env.test.local
.env.production.local
```

**Comment by Miyunecadz** [comment]
Thank you for your advice, but i already add .env in my .gitignore. I just
forgot to delete it.

**Comment by acatzk** [comment]
You need to add more

**Comment by Miyunecadz** [comment]
what do you mean to add more?

**Comment by Miyunecadz** [comment]
For now i think that's all i need to ignore. the env file and the node
modules

**Comment by acatzk** [comment]
> what do you mean to add more?

What I mean is that for some reasons we might to
 have .env for local, development and production so
it's always be prepared to ignore it during commit.

But anyways I'm just sharing.
![image](https://user-images.githubusercontent.com/38458781/114952653-4af1c980-9e89-11eb-8403-7c0d3bb8791d.png)

**Comment by acatzk** [comment]
You may close it afterwards

**Comment by Miyunecadz** [comment]
ahh, okay thank you for that wonderful knowledge that you shared with me,
im also aware of that. It also good to remind someone. thank you so much.
have a good day! Happy Coding! 😃
